@startuml
concise "Öffentlichkeit" as public
robust "Projekt" as proj
concise "Jury" as jury
concise "Orga Team" as orga

@29
orga is supporting

@+2
proj is NOMINIERT
public -> proj : nominieren

@+1
orga -> jury : nominieren
jury is Zusammenstellung

@+2
proj is BEWERBUNG

@+1
jury is "Top 3"
orga -> jury : BBB

@+2
jury is "Gewinner"
jury -> orga : informieren

@+1
proj is "in TOP 3"
orga -> public : publish

@+1
jury is "Session"
orga -> jury
jury -> orga : znacht

@+4
orga -> jury
jury -> orga : BBB
jury is "DINAcon"

@+1
proj is Gewinner
orga -> public : publish
jury is {-}
@enduml
